services:
  - type: web
    name: fastapi-workout-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port $PORT
    env: python

